name: build-and-test

# Quando isso deve rodar?
on:
  push:
    branches: ["main"] # Sempre que der push na main
  pull_request:
    branches: ["main"] # Sempre que abrir um PR para main

# O que ele deve fazer?
jobs:
  build-and-test:
    runs-on: ubuntu-latest # Aluga uma máquina Ubuntu (Linux)

    steps:
      # 1. Baixa o seu código na máquina
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instala o Node.js v18 (ou a que vc usa)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm" # Cacheia para ser mais rápido na próxima

      # 3. Instala dependências (npm ci é mais rápido e seguro que npm install)
      - name: Install dependencies
        run: npm ci

      # 4. Roda os testes
      # A MÁGICA: Como fizemos testes unitários com Mocks,
      # não precisamos subir o Docker/Postgres aqui! O teste roda isolado.
      - name: Run Tests
        run: npm test
